In [1]:
import numpy as np
import pandas as pd
import warnings 
warnings.simplefilter('ignore')

In [2]:
df=pd.read_csv('Wine.csv')
df.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [3]:
df.Customer_Segment.value_counts()

Customer_Segment
2    71
1    59
3    48
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [5]:
X= df.iloc[:,:13]
y= df.iloc[:,13]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.3)

# without pca

In [7]:

from sklearn.neighbors import KNeighborsClassifier
# model
knn_model=KNeighborsClassifier()

knn_model.fit(X_train,y_train)

# prediction
print('*'*20)
train_prediction= knn_model.predict(X_train)
test_prediction= knn_model.predict(X_test)

# evaluation
print('*'*20)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,test_prediction))
print(accuracy_score(y_train,train_prediction))

# cross validation score
print('*'*20)

from sklearn.model_selection import cross_val_score
score= cross_val_score(knn_model,X,y,cv=5)
print(score)
score.mean()

********************
********************
0.7407407407407407
0.7741935483870968
********************
[0.72222222 0.66666667 0.63888889 0.65714286 0.77142857]


0.6912698412698413

In [8]:
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()
log_model.fit(X_train,y_train)

# prediction
print('*'*20)
train_prediction= log_model.predict(X_train)
test_prediction= log_model.predict(X_test)

# evaluation
print('*'*20)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,test_prediction))
print(accuracy_score(y_train,train_prediction))

# cross validation score
print('*'*20)

from sklearn.model_selection import cross_val_score
score= cross_val_score(knn_model,X,y,cv=5)
print(score)
score.mean()

********************
********************
0.9814814814814815
0.9596774193548387
********************
[0.72222222 0.66666667 0.63888889 0.65714286 0.77142857]


0.6912698412698413

# with PCA 

In [9]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X= sc.fit_transform(X)

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.3)

In [11]:
from sklearn.decomposition import PCA

pca_model = PCA(n_components=0.95)

X_train_pca = pca_model.fit_transform(X_train)

X_test_pca = pca_model.transform(X_test)

In [12]:
X_train_pca.shape

(124, 10)

In [13]:
pca_model.explained_variance_ratio_

array([0.36534816, 0.18061255, 0.11686462, 0.07930205, 0.07138901,
       0.04610997, 0.03442149, 0.02730303, 0.02105357, 0.01980785])

In [14]:
## 
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()
log_model.fit(X_train_pca,y_train)

# prediction
print('*'*20)
train_prediction= log_model.predict(X_train_pca)
test_prediction= log_model.predict(X_test_pca)

# evaluation
print('*'*20)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,test_prediction))
print(accuracy_score(y_train,train_prediction))

# cross validation score
print('*'*20)

from sklearn.model_selection import cross_val_score
score= cross_val_score(log_model,X,y,cv=5)
print(score)
score.mean()

********************
********************
0.9814814814814815
1.0
********************
[0.97222222 0.97222222 1.         1.         1.        ]


0.9888888888888889

In [16]:
## 
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier()
knn_model.fit(X_train_pca,y_train)

# prediction
print('*'*20)
train_prediction= knn_model.predict(X_train_pca)
test_prediction= knn_model.predict(X_test_pca)

# evaluation
print('*'*20)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,test_prediction))
print(accuracy_score(y_train,train_prediction))

# cross validation score
print('*'*20)

from sklearn.model_selection import cross_val_score
score= cross_val_score(log_model,X,y,cv=5)
print(score)
score.mean()

********************
********************
0.9629629629629629
0.9838709677419355
********************
[0.97222222 0.97222222 1.         1.         1.        ]


0.9888888888888889